### ISSUE TITLE
Doesn't use the correct pane

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-cursor-history#22]
If I have the same file open in two different panes, using cursor-history always jumps to the first pane (leftmost), even if I'm currently editing in the second pane.

**Comment by t9md** [comment]
~~Not sure what you are saying.~~
~~From quick check, it's not happen in my environment.~~

~~Somewhat similar issue is observed when you enabled "Search All Panes" features.~~
~~Do you have it enabled? If so I have idea to improve this.~~

<img width="637" alt="settings_ ___github_atom-cursor-history" src="https://cloud.githubusercontent.com/assets/155205/19616882/be21dd8a-985a-11e6-8ca2-f103f6c5404c.png">

**Comment by t9md** [comment]
~~BeWhat I changed is order to find editor to open~~
~~1. current editor~~
~~2. from current active pane if item was already opened~~
~~3. open new editor in active pane, optionally searchAllPanes for already opened item.~~

~~2nd one is I added this change.~~
~~Does this what you are mentioning?~~

**Comment by t9md** [comment]
Because of bug, the issue you reported was exists with default configuration.

I cleanup and fixed two bug.
1. Even if history entry is at same editor, it didn't try to use same editor
   So if more than two pane was opened and same buffer(editor with same filePath) was opened in other pane, leftmost pane's editor was used if `searchAllPanes` was set to `true`(default setting).
2. Even if If history entry is at editor opened in same pane, it didn't use that same pane's editor.

Both are fixed so please check with latest version v0.7.0.
Thanks for notifying this bug.

And welcome for other improvement ideas or other frustration you want to be fixed.

**Comment by t9md** [comment]
@chenglou Solved?

**Comment by chenglou** [comment]
Sorry, been busy and forgot about this completely. Yes, it's now fixed! Thanks a lot!
