### ISSUE TITLE
Doesn't work on hyperclick

### ISSUE THREAD

**Issue by aki77** [t9md/atom-cursor-history#32]
It would be nice if  support for [hyperclick](https://atom.io/packages/hyperclick).

[![https://gyazo.com/5cfaa0f8c2acdda19b6917caafeeec1c](https://i.gyazo.com/5cfaa0f8c2acdda19b6917caafeeec1c.gif)](https://gyazo.com/5cfaa0f8c2acdda19b6917caafeeec1c)

**Comment by t9md** [comment]
I checked and now understand why it's not work.
I'm not hyperclick user currently.

I'll back when I'm motivated to support hyperclick.
Here is memo what I investigated very quickly.

- What cursor-history package doing on normal mouse click event is( normal mouse click just move cuursor to clicked position )
  - Save location(filePath and cursor position) on mouse-event **capture** phase(at this point cursor is still at old position)
  - Compare location after `100ms` of mouse-event **bubbling** phase(at this point, cursor is at new position)
  - Comparison is done by diff of row, diff of filePath, diff of cursor column within same row(optional).
  - Then comparison result met criteria to save to history, update history.

- But when hyperclick click, it won't fire 2nd mouse-event **bubbling** phase, in other word, hyperclick intentionally prevent propagation of mouse event. So cursor-history have no chance to know the timing to compare with old and new locaiton.

- The fix idea is to start observation of cursor position change on captureing phase of click.
- Then cursor position was changed, compare location(filePath, position).
- I'm intentionally basically avoiding to use `editor.onDidChangeCursorPosition`
- I used in old code of this package, but removed to avoid mis-memorizing history because of so many package update cursor position with intent or without intent, that mess up history(means save useless cursor position, e.g just cmd-r to refer symbols-view update cursor position and update history if I natively use `onDidChangeCursorPosition`).

Will back when I have time, thanks for input!

**Comment by aki77** [comment]
Thank you for your help. 😄 
I can wait.

**Comment by t9md** [comment]
I haven't checked throughly, do you have time to check the behavior from this repo?

CHANGES from released version are

- history serialize/deserialization with normal Atom's serialization mechanism(thus history is maintained per project not per Atom-wide)
- hyperclick support( open new file via mouse and mouse event is not propagated situation )

**Comment by aki77** [comment]
Noted with thanks!

**Comment by aki77** [comment]
It's a perfect! Thank you. 👍

**Comment by t9md** [comment]
OK, thanks, maybe release at tomorrow.
Thanks for checking how it works, was great help 👍
